project_identifier: sonar-l10-ru
api_key: <%= ENV["CROWDIN_API_KEY"] %>

files:
  -
    source: '/src/main/resources/org/sonar/l10n/core.properties'
    dest: '/core.properties'
    translation: '<%= ENV["GIT_LOCAL_BRANCH"] %>/src/main/resources/org/sonar/l10n/core_%two_letters_code%.properties'
    type: 'properties'

  -
    source: '/src/main/resources/org/sonar/l10n/motionchart.properties'
    dest: '/motionchart.properties'
    translation: '<%= ENV["GIT_LOCAL_BRANCH"] %>/src/main/resources/org/sonar/l10n/motionchart_%two_letters_code%.properties'
    type: 'properties'
