name: Grammar check

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
      - name: Run yaspeller
        run: |
          sudo npm install yaspeller -g
          yaspeller ./src/main/resources/org/sonar/l10n/core_ru.properties --ignore-latin --ignore-capitalization